-- Makes the public demo account's readings read-only (generated by scripts/seed-demo.mjs).
-- Run in the Supabase SQL Editor AFTER seeding. Insights stay writable so the
-- Ask-AI rate limit keeps working for demo visitors.

drop policy if exists "demo readings read-only insert" on public.readings;
create policy "demo readings read-only insert" on public.readings
  as restrictive for insert to authenticated
  with check (auth.uid() <> 'ad9d6915-07d7-4cd1-aa09-7a325ff80c50');

drop policy if exists "demo readings read-only update" on public.readings;
create policy "demo readings read-only update" on public.readings
  as restrictive for update to authenticated
  using (auth.uid() <> 'ad9d6915-07d7-4cd1-aa09-7a325ff80c50');

drop policy if exists "demo readings read-only delete" on public.readings;
create policy "demo readings read-only delete" on public.readings
  as restrictive for delete to authenticated
  using (auth.uid() <> 'ad9d6915-07d7-4cd1-aa09-7a325ff80c50');
