// Seeds the public demo account with ~6 months of realistic readings.
// Idempotent: re-running replaces the demo user's readings and cached insights.
// Run BEFORE applying db/demo-readonly.sql (which this script generates).
//   node scripts/seed-demo.mjs
import { createClient } from "@supabase/supabase-js";
import { readFileSync, writeFileSync } from "node:fs";

export const DEMO_EMAIL = "mybiomarker.demo@gmail.com";
export const DEMO_PASSWORD = "demo-mybiomarker-2026";

// Minimal .env.local loader (no dotenv dependency)
const env = Object.fromEntries(
  readFileSync(new URL("../.env.local", import.meta.url), "utf8")
    .split("\n")
    .filter((l) => l.includes("=") && !l.startsWith("#"))
    .map((l) => [l.slice(0, l.indexOf("=")).trim(), l.slice(l.indexOf("=") + 1).trim()]),
);

const supabase = createClient(
  env.NEXT_PUBLIC_SUPABASE_URL,
  env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
);

// slug → [date, value, value_2?][]
const SERIES = {
  fasting_glucose: [
    ["2026-02-10", 108], ["2026-03-14", 104], ["2026-04-18", 101],
    ["2026-05-16", 98], ["2026-06-13", 95], ["2026-07-11", 92],
  ],
  blood_pressure: [
    ["2026-02-10", 126, 82], ["2026-03-28", 130, 84], ["2026-05-02", 134, 86],
    ["2026-06-06", 138, 88], ["2026-07-11", 142, 90],
  ],
  ldl: [["2026-02-10", 162], ["2026-04-18", 148], ["2026-06-13", 138]],
  hdl: [["2026-02-10", 46], ["2026-04-18", 52], ["2026-06-13", 58]],
  triglycerides: [["2026-02-10", 190], ["2026-04-18", 160], ["2026-06-13", 138]],
  hs_crp: [["2026-02-10", 3.4], ["2026-04-18", 2.1], ["2026-06-13", 1.4]],
};

async function main() {
  let { data: auth } = await supabase.auth.signInWithPassword({
    email: DEMO_EMAIL,
    password: DEMO_PASSWORD,
  });
  if (!auth?.user) {
    const { data: signedUp, error } = await supabase.auth.signUp({
      email: DEMO_EMAIL,
      password: DEMO_PASSWORD,
    });
    if (error || !signedUp.session) {
      throw new Error(`Could not create demo user: ${error?.message ?? "no session (email confirmation on?)"}`);
    }
    auth = signedUp;
  }
  const userId = auth.user.id;
  console.log(`Demo user: ${userId}`);

  const { data: catalog, error: catErr } = await supabase.from("biomarker_types").select("id, slug");
  if (catErr) throw catErr;
  const idBySlug = Object.fromEntries(catalog.map((t) => [t.slug, t.id]));

  await supabase.from("readings").delete().eq("user_id", userId);
  await supabase.from("insights").delete().eq("user_id", userId);

  const rows = Object.entries(SERIES).flatMap(([slug, series]) =>
    series.map(([tested_at, value, value_2]) => ({
      user_id: userId,
      biomarker_id: idBySlug[slug],
      value,
      value_2: value_2 ?? null,
      tested_at,
      source: "Demo data",
      notes: null,
    })),
  );
  const { error: insertErr } = await supabase.from("readings").insert(rows);
  if (insertErr) throw insertErr;
  console.log(`Inserted ${rows.length} readings.`);

  writeFileSync(
    new URL("../db/demo-readonly.sql", import.meta.url),
    `-- Makes the public demo account's readings read-only (generated by scripts/seed-demo.mjs).
-- Run in the Supabase SQL Editor AFTER seeding. Insights stay writable so the
-- Ask-AI rate limit keeps working for demo visitors.

drop policy if exists "demo readings read-only insert" on public.readings;
create policy "demo readings read-only insert" on public.readings
  as restrictive for insert to authenticated
  with check (auth.uid() <> '${userId}');

drop policy if exists "demo readings read-only update" on public.readings;
create policy "demo readings read-only update" on public.readings
  as restrictive for update to authenticated
  using (auth.uid() <> '${userId}');

drop policy if exists "demo readings read-only delete" on public.readings;
create policy "demo readings read-only delete" on public.readings
  as restrictive for delete to authenticated
  using (auth.uid() <> '${userId}');
`,
  );
  console.log("Wrote db/demo-readonly.sql — paste it into the Supabase SQL Editor.");
  await supabase.auth.signOut();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
